server.port=8090
spring.jpa.hibernate.ddl-auto=update

##CLOUD-SQL-CONFIGURATIONS
spring.cloud.gcp.sql.database-name=reservations
spring.cloud.gcp.sql.instance-connection-name=reto2dolab-344800:us-central1:reservations
# So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
# Enforces database initialization
spring.datasource.initialization-mode=always
spring.datasource.username=root
spring.datasource.password=root
spring.cloud.gcp.project-id=reto2dolab-344800
spring.cloud.gcp.credentials.location=classpath:reto2dolab-344800-2798c924f539.json

#RabbitMQ-CONFIGURATIONS
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
reto2.microservices.apireservations.rabbitmq.exchange=apireservations.exchange
reto2.microservices.apireservations.rabbitmq.queue=apireservations.queue
reto2.microservices.apireservations.rabbitmq.routingkey=apireservations.routingkey